Re-enable OpenOCD module with version pinning
- Add openocd module back to MODULES list in config
- Pin OpenOCD to stable rp2040-v0.12.0 branch instead of rp2040-master
- Add --disable-werror flag to fix compilation issues
- Add installation verification step
- Remove empty BuildOS_new.yml workflow file

diff --git a/OpenMowerOS/src/modules/openocd/start_chroot_script b/OpenMowerOS/src/modules/openocd/start_chroot_script
--- a/OpenMowerOS/src/modules/openocd/start_chroot_script
+++ b/OpenMowerOS/src/modules/openocd/start_chroot_script
@@ -14,15 +14,19 @@ echo "Installing OpenOCD dependencys"
 apt-get update --allow-releaseinfo-change
 apt-get install --yes --no-install-recommends git autoconf automake build-essential pkg-config texinfo libtool libftdi-dev libusb-1.0-0-dev rpi.gpio-common
 
-echo "Installing OpenOCD"
-git clone https://github.com/raspberrypi/openocd.git --recursive --branch rp2040-master --depth=1
+echo "Installing OpenOCD rp2040-v0.12.0"
+git clone https://github.com/raspberrypi/openocd.git --recursive --branch rp2040-v0.12.0 --depth=1
 cd openocd
 ./bootstrap
-./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio
+./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio --disable-werror
 make -j$(nproc)
 make install
 cd ..
 rm -rf openocd
+
+# Verify OpenOCD installation
+echo "Verifying OpenOCD installation..."
+openocd --version || echo "Warning: OpenOCD installation verification failed"
 
 
 
